### ISSUE TITLE
go-jsonnet build with Python 3.13+

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-spack#29]
A change in Python3.13 breaks go-jsonnet

- okay: `spack install go-jsonnet@0.19.1 +python`
- fail: `spack install go-jsonnet@0.19.1 +python`
- okay: `spack install -j 20 go-jsonnet@0.19.1 +python ^python@3.12`
- fail: `spack install -j 20 go-jsonnet@0.19.1 +python ^python@3.13`
- okay: `spack install -j 20 go-jsonnet@0.21.0 +python ^python@3.13`
- okay: `spack install -j 20 go-jsonnet@0.21.0 +python ^python@3.12`

Last after adding new versions, not yet pushed.

The problem is due to an API change to Python in 3.13.  This was spotted upstream: https://github.com/google/go-jsonnet/issues/775 fixed Feb 18, 2025 and probably first in v0.21.0-rc1.

So, for go-jsonnet v0.20.0 and older we need to constrain to use python 3.12 or older.

As part of investigating this problem, other related problems:

- Spack 1.1 requires packages to depend on compilers (`depends_on("c")` and `depends_on("cxx")`)
- go-jsonnet does not need c/c++ just for the command line programs.
- go-jsonnet does need these for either the python bindings or to provide the shared lib.

For reference, failure errors are like:

```
  >> 95     python/_jsonnet.c:189:14: error: implicit declaration of function 'PyEval_CallObject'; did you mean 'PyObject_CallObject'?
             [-Wimplicit-function-declaration]
     96         189 |     result = PyEval_CallObject(ctx->callback, arglist);
     97             |              ^~~~~~~~~~~~~~~~~
     98             |              PyObject_CallObject
  >> 99       python/_jsonnet.c:189:12: error: assignment to 'PyObject *' {aka 'struct _object *'} from 'int' makes pointer from integ
            er without a cast [-Wint-conversion]
     100        189 |     result = PyEval_CallObject(ctx->callback, arglist);
     101            |            ^
     102      python/_jsonnet.c: In function 'cpython_import_callback':
  >> 103      python/_jsonnet.c:229:12: error: assignment to 'PyObject *' {aka 'struct _object *'} from 'int' makes pointer from integ
            er without a cast [-Wint-conversion]
     104        229 |     result = PyEval_CallObject(ctx->callback, arglist);
     105            |            ^
```
